name: sarprasonlinemobile
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  json_annotation: ^4.4.0
  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8
  flutter:
    sdk: flutter
  url_launcher: ^6.0.9
  font_awesome_flutter: ^10.1.0
  animations: ^2.0.0
  google: ^0.0.1
  shared_preferences: ^2.0.6
  flutter_spinkit: ^5.1.0
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.0
  get: ^4.6.5
  image_picker: ^1.1.1
  google_sign_in: ^6.2.1
  http: ^1.2.0
  pdf: ^3.6.0
  printing: ^5.6.1
  intl: ^0.19.0
  quickalert: ^1.1.0
  accordion: ^2.6.0
  expansion_widget: ^0.1.0
  
  
  omni_datetime_picker: ^1.1.0
  cloud_firestore: ^4.17.3
  path: ^1.8.3
  sqflite: ^2.3.2

dev_dependencies:
  build_runner: ^2.1.0
  json_serializable: ^6.0.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
